### ISSUE TITLE
Please exclude EPEL configuration

### ISSUE THREAD

**Issue by wAmpIre** [stdevel/ansible-omd#4]
Hi!

Good work, THX!

But please exclude configuration of EPEL repository on CentOS/RHEL into its own role. This should only be an (meta) dependency on "epel".

**Comment by stdevel** [comment]
Hi @wAmpIre,
thanks for the feedback!

What do you mean by "meta dependency on epel"? How would an implementation look like in `meta/main.yml`?
I understand there are several roles on Ansible Galaxy that could enable/configure EPEL, such as `geerlingguy/repo-epel` - I could add this role as dependency.

**Comment by stdevel** [comment]
Fixed in commit e79183fe224b7a3d2fe720607ba29e191b90a839.
